In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [64]:
dataset=pd.read_csv('train_2kmZucJ.csv')

In [65]:
dataset.head()

id  label                                              tweet
0   1      0  #fingerprint #Pregnancy Test https://goo.gl/h1...
1   2      0  Finally a transparant silicon case ^^ Thanks t...
2   3      0  We love this! Would you go? #talk #makememorie...
3   4      0  I'm wired I know I'm George I was made that wa...
4   5      1  What amazing service! Apple won't even talk to...

In [66]:
dataset.shape

(7920, 3)

In [67]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus=[]
for i in range(0,7920):
    review=re.sub('[^a-zA-Z]',' ',dataset['tweet'][i])
    review=review.lower()
    review=review.split()
    ps=PorterStemmer()
    all_stopwords=stopwords.words('english')
    all_stopwords.remove('not')
    review=[ps.stem(word) for word in review if not word in set(all_stopwords)]
    review=' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rajat1\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [68]:
print(corpus)

['fingerprint pregnanc test http goo gl h mfqv android app beauti cute health iger iphoneonli iphonesia iphon', 'final transpar silicon case thank uncl yay soni xperia sonyexperia http instagram com p yget jc jm', 'love would go talk makememori unplug relax iphon smartphon wifi connect http fb n lsupcu', 'wire know georg made way iphon cute daventri home http instagr p li uj k', 'amaz servic appl even talk question unless pay stupid support', 'iphon softwar updat fuck phone big time stupid iphon', 'happi us instap instadaili us soni xperia xperiaz http instagram com p z qgfwlvj', 'new type c charger cabl uk http www ebay co uk itm bay amazon etsi new year rob cross tobi young evemun mcmafia taylor spectr newyear start recip technolog samsunggalaxi iphonex pic twitter com pjiwq wtc', 'bout go shop listen music iphon justm music likeforlik followforfollow http instagr p vj bg tlql', 'photo fun selfi pool water soni camera picoftheday sun instagood boy cute outdoor http tmblr co zajc n ms

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1500)
X=cv.fit_transform(corpus).toarray()
y=dataset.iloc[:,1].values

In [70]:
#from sklearn.naive_bayes import GaussianNB
#gnb=GaussianNB()
#gnb.fit(X,y)

In [71]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
rfc.fit(X,y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [72]:
test_data=pd.read_csv('test_oJQbWVk.csv')

In [73]:
test_data.head()

id                                              tweet
0  7921  I hate the new #iphone upgrade. Won't let me d...
1  7922  currently shitting my fucking pants. #apple #i...
2  7923  I'd like to puts some CD-ROMS on my iPad, is t...
3  7924  My ipod is officially dead. I lost all my pict...
4  7925  Been fighting iTunes all night! I only want th...

In [74]:
final_data=test_data.drop(['id'],axis=1)

In [75]:
final_data.head()

tweet
0  I hate the new #iphone upgrade. Won't let me d...
1  currently shitting my fucking pants. #apple #i...
2  I'd like to puts some CD-ROMS on my iPad, is t...
3  My ipod is officially dead. I lost all my pict...
4  Been fighting iTunes all night! I only want th...

In [76]:
final_data.shape

(1953, 1)

In [77]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus1=[]
for i in range(0,1953):
    review=re.sub('[^a-zA-Z]',' ',final_data['tweet'][i])
    review=review.lower()
    review=review.split()
    ps=PorterStemmer()
    all_stopwords=stopwords.words('english')
    all_stopwords.remove('not')
    review=[ps.stem(word) for word in review if not word in set(all_stopwords)]
    review=' '.join(review)
    corpus1.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rajat1\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [78]:
final_data=cv.fit_transform(corpus1).toarray()

In [79]:
print(final_data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [80]:
y_predicted=rfc.predict(final_data)

In [81]:
submission = pd.DataFrame({
        "id": test_data['id'],
        "label": y_predicted
    })

In [82]:
submission.to_csv('Identifythesentiments_submission3.csv', index=False)